# Generated by Django 2.1 on 2018-09-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='uploaded_images')),
            ],
        ),
        migrations.CreateModel(
            name='CoOccur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_book', to='app.Book')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted', to='app.Character')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourced', to='app.Character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='co_occurences',
            field=models.ManyToManyField(blank=True, through='app.CoOccur', to='app.Character'),
        ),
    ]
